### ISSUE TITLE
How to add dynamic events?

### ISSUE THREAD

**Issue by hdr105** [fourlabsldn/fl-booking-js#1]
I am trying to store json of dynamic events in a variable like this.

var abc = '{"data":[{"start":"2018-05-14T11:00","end":"2018-05-14T11:30"},{"start":"2018-05-15T11:00","end":"2018-05-15T11:30"}]}';

and using this variable in getevents function like this

  getEvents: data => (abc),

But this is not working.

Can you please help?

**Comment by jonny-no1** [comment]
Your date/time string needs to follow this format: `2016-11-02T12:00:00.000Z`
